### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by asal500**
Hello,

I want to upload first week assignment.

thank you

### CODE REVIEW

**Review by bnajafi — COMMENTED** [review]
Please only include a pdf file with the correct file name

**Comment by asal500** [comment]
[week1-FJafari.pdf](https://github.com/bnajafi/TES_2019-2020_weeklySubmissions/files/3711623/week1-FJafari.pdf)

**Comment by asal500** [comment]
hi week 1 task 1

**Comment by asal500** [comment]
Hi,
I uploaded my first week assignment many days ago but I couldn't see my name in week 1 folder.
[week1-FJafari.pdf](https://github.com/bnajafi/TES_2019-2020_weeklySubmissions/files/3724367/week1-FJafari.pdf)

**Comment by asal500** [comment]
[Week3_FJafari.pdf](https://github.com/bnajafi/TES_2019-2020_weeklySubmissions/files/3761006/Week3_FJafari.pdf)

**Pull request merged**
