### PR TITLE
assignment

### PR DESCRIPTION
**Pull request by Mhamada95**

### CODE REVIEW

**Comment by Mhamada95** [comment]
week6

**Comment by Mhamada95** [comment]
[week6_Mhamada.pdf](https://github.com/bnajafi/TES_2019-2020_weeklySubmissions/files/3838282/week6_Mhamada.pdf)

**Comment by bnajafi** [comment]
You pull request for some reason is removing submission of other 1 students, please check on this before I accept th merge

**Comment by Mhamada95** [comment]
ok i will pull the request again. That's all I can do !
[week6_Mhamada.pdf](https://github.com/bnajafi/TES_2019-2020_weeklySubmissions/files/3844403/week6_Mhamada.pdf)

**Comment by Mhamada95** [comment]
[week7_Mhamada.pdf](https://github.com/bnajafi/TES_2019-2020_weeklySubmissions/files/3866604/week7_Mhamada.pdf)

**Comment by Mhamada95** [comment]
[TASK 8.pdf](https://github.com/bnajafi/TES_2019-2020_weeklySubmissions/files/3894714/TASK.8.pdf)

**Comment by Mhamada95** [comment]
[WEEK8_Mhamada.pdf](https://github.com/bnajafi/TES_2019-2020_weeklySubmissions/files/3894720/WEEK8_Mhamada.pdf)

**Comment by Mhamada95** [comment]
[week9_Mhamada.pdf](https://github.com/bnajafi/TES_2019-2020_weeklySubmissions/files/3921333/week9_Mhamada.pdf)

**Pull request closed without merging**
